title: piece
extends@: default

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            header.show_page:
              type: toggle
              label: Accessible en tant que page
              default: 0
              options:
                1: PLUGIN_ADMIN.YES
                0: PLUGIN_ADMIN.NO
              validate:
                type: bool
              ordering@: 1


            header.collaboration:
              label: Collaboration
              toggleable: true
              type: select
              data-options@: ['\Grav\Theme\Luvan::data', 'people']
              multiple: true
              validate:
                type: array

            spacer:
              type: spacer
              title: ' '

            basic_info:
              type: section
              title: Informations de base

            columns:
              type: columns

              fields:
                column1:
                  type: column

                  fields:
                    header.date:
                      label: Date de parution
                      type: datetime

                    header.notes:
                      label: Notes
                      type: text
                      help: le texte s'affichera entre parenthèses dans la liste des projets

                    if_paper:
                      type: conditional
                      condition: context.parent().slug in ['books', 'collectives', 'periodics']

                      import@:
                        type: partials/publisher
                        context: blueprints://

                    if_theater:
                      type: conditional
                      condition: context.parent().slug is same as('theater')

                      import@:
                        type: partials/theater
                        context: blueprints://

                column2:
                  type: column

                  fields:
                    header.external_link:
                      label: Lien externe
                      type: text
                      placeholder: '[text affiché](url)'
                      help: Exemple : [Chez l'éditeur](https://lavolte.net/livres/susto/)

                    header.extra_text:
                      label: Texte extra
                      type: text
                      help: le texte s'affichera à la fin dans la liste des projets

                    if_paper:
                      type: conditional
                      condition: context.parent().slug in ['books', 'collectives']

                      import@:
                        type: partials/mep
                        context: blueprints://

                    if_theater_perf:
                      type: conditional
                      condition: context.parent().slug in ['theater', 'performances']

                      import@:
                        type: partials/representation
                        context: blueprints://

            if_radio:
              type: conditional
              condition: context.parent().slug is same as('radio')

              fields:
                header.production:
                  type: text
                  label: Production (markdown)

            content:
              type: markdown
              validate:
                type: textarea

            header.media_order:
              type: pagemedia
              label: PLUGIN_ADMIN.PAGE_MEDIA

            extra:
              type: fieldset
              title: Extra
              collapsed: true
              collapsible: true

              fields:
                header.nominations:
                  type: list
                  label: Nominations
                  style: vertical

                  fields:
                    .name:
                      type: text
                      label: Nom
                    .year:
                      type: text
                      label: Année
                    .url:
                      type: text
                      label: URL
                      placeholder: Optionnel

                header.awards:
                  type: list
                  label: Prix
                  style: vertical

                  fields:
                    .name:
                      type: text
                      label: Nom
                    .year:
                      type: text
                      label: Année
                    .url:
                      type: text
                      label: URL
                      placeholder: Optionnel

                header.grants:
                  type: list
                  label: Bourses
                  style: vertical

                  fields:
                    .name:
                      type: text
                      label: Nom
                    .year:
                      type: text
                      label: Année
                    .url:
                      type: text
                      label: URL
                      placeholder: Optionnel
